version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  http:
    build:
      context: .
      dockerfile: docker/Dockerfile.http
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  db_data:

