# docker/Dockerfile.frontend
FROM node:18

WORKDIR /app

# Instala Vue CLI
RUN npm install -g @vue/cli

# Copiamos el código de frontend
COPY ../front-end /app

# Instala dependencias de Vue
RUN npm install

# Expone el puerto de desarrollo de Vue.js
EXPOSE 8080

# Comando de ejemplo (cambia según el framework)
CMD ["npm", "run", "serve"]

