FROM node:14 AS frontend

WORKDIR /app/frontend
COPY ./frontend/package.json /app/frontend/
RUN npm install
COPY ./frontend/ /app/frontend/
RUN npm run build

FROM python:3.9-slim AS backend

WORKDIR /app/backend
COPY ./backend/requirements.txt /app/backend/
RUN pip install -r requirements.txt
COPY ./backend/ /app/backend/

COPY --from=frontend /app/frontend/dist /app/backend/static

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

