# Usa la imagen base de Node.js 18
FROM node:18
WORKDIR /app

# Copia solo package.json y package-lock.json para aprovechar la caché de Docker
COPY ../frontend/src/package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código restante del frontend al contenedor
COPY ../frontend .

# Expone el puerto 8080 para el desarrollo de Vue.js
EXPOSE 8080

# Comando para iniciar el servidor de desarrollo de Vue.js
CMD ["npm", "run", "serve"]
