# docker/Dockerfile.backend
FROM python:3.9-slim

WORKDIR /app

# Instala Django
RUN pip install django

# Copiamos el código de backend
COPY ../back-end /app

# Expone el puerto de Django
EXPOSE 8000

# Comando de ejemplo (cambia según el framework)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

