# docker/Dockerfile.db
FROM mysql:8

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=example
ENV MYSQL_DATABASE=proyecto
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

